### ISSUE TITLE
Template version

### ISSUE THREAD

**Issue by guiwitz** [SwissDataScienceCenter/contributed-project-templates#77]
When using the templates to create a new project on renkulab, the system still uses the version 0.6 of the contributed templates (at least for the desktop one that I tested). The main issue with that is that 0.6 still uses conda for environments while 0.7 uses mamba. As conda has become almost unusable these days, this makes builds fail at the stage of environment solving and for people not very familiar with conda this might be difficult to debug. Could renkulab use the most recent version of the contributed projects?

**Comment by rokroskar** [comment]
Thanks for pointing that out @guiwitz and apologies for missing this - it will be in the next release: https://github.com/SwissDataScienceCenter/renku/pull/3536
